#!/bin/bash

VAR_LIB_PGBACKREST=$SNAP_COMMON/var/lib/pgbackrest
INSTALL_CMD=$SNAP/usr/bin/install
$INSTALL_CMD -d -m 750 $SNAP_DATA/etc/testtest
echo "testing"
ls -lah $SNAP_DATA/etc
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_DATA/etc/patroni
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_DATA/etc/postgresql
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_DATA/etc/pgbackrest
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_DATA/etc/pgbouncer

$INSTALL_CMD -d -m 750 -o 584788 -g 0 $VAR_LIB_PGBACKREST
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_COMMON/postgresql.failed
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_COMMON/data/db

$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_COMMON/var/lib/postgresql
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_COMMON/var/log/patroni
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_COMMON/var/log/pgbackrest
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_COMMON/var/log/pgbouncer
$INSTALL_CMD -d -m 750 -o 584788 -g 0 $SNAP_COMMON/var/log/postgresql

# hack : patroni_raft_controller cant create
#mkdir -p $SNAP_COMMON/raft
#mkdir -p $SNAP_COMMON/postgresql
#mkdir -p $SNAP_DATA/postgresql
#touch $SNAP_DATA/postgresql/postgresql.conf
#touch $SNAP_DATA/postgresql/pg_ident.conf

# cp $SNAP/config/patroni.yaml $SNAP_DATA/etc/patroni
# cp $SNAP/etc/pgbackrest.conf $SNAP_DATA/etc/pgbackrest
$INSTALL_CMD -m 750 -o 584788 -g 0 $SNAP/config/patroni.yaml $SNAP_DATA/etc/patroni
$INSTALL_CMD -m 750 -o 584788 -g 0 $SNAP/etc/pgbackrest.conf $SNAP_DATA/etc/pgbackrest

sed -i "s:/var/lib/pgbackrest:$VAR_LIB_PGBACKREST:g" $SNAP_DATA/etc/pgbackrest/pgbackrest.conf
echo "pg1-path=$SNAP_COMMON/var/lib/postgresql" >> $SNAP_DATA/etc/pgbackrest/pgbackrest.conf
echo "pg1-user=snap_daemon" >> $SNAP_DATA/etc/pgbackrest/pgbackrest.conf

# hack 
# chmod -R 777 "$SNAP_COMMON"
# chmod -R 777 "$SNAP_DATA"
#
# chown -R 584788:root $SNAP_COMMON/*
# chown -R 584788:root $SNAP_DATA/*
